name: Compile code with javac
on: [ push ]
jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Code
        run: chmod +x build-lin.sh && ./build-lin.sh

      - name: Run Tests
        run: java -cp ./out TestRunner test-db 1024 100