name: Compile code with javac
on: [ push ]
jobs:
  compile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Code
        run: find ./src -name "*.java" > sources.txt && javac @sources.txt